-- business analysis


USE olist_analysis;
-- created a wrong column(Overall_spent) in excel, but will drop using sql
ALTER TABLE payments
DROP COLUMN Overall_spent;

-- 1 Total revenue generated by Olist is $16008872.12
SELECT SUM(payment_value) 
FROM payments;

-- 2 Olist has a total number of 103886 orders with a total income of $16008872.12
SELECT COUNT(order_id) AS Number_Of_Orders
FROM payments;

-- 3 this query shows how sales changed over time
SELECT
    YEAR(o.order_purchase_timestamp) AS year,
    MONTH(o.order_purchase_timestamp) AS month,
    SUM(p.payment_value) AS monthly_revenue
FROM orders o
JOIN payments p
ON o.order_id = p.order_id
GROUP BY
    YEAR(o.order_purchase_timestamp),
    MONTH(o.order_purchase_timestamp)
ORDER BY
    year,
    month;
    
-- 4 caculating the monthly growth
WITH monthly_sales AS
(
    SELECT
        DATE_FORMAT(o.order_purchase_timestamp,'%Y-%m') AS sales_month,
        SUM(p.payment_value) AS revenue
    FROM orders o
    JOIN payments p
    ON o.order_id = p.order_id
    GROUP BY DATE_FORMAT(o.order_purchase_timestamp,'%Y-%m')
)

SELECT
    sales_month,
    revenue,
    ROUND(
        (
        revenue - LAG(revenue) OVER(ORDER BY sales_month)
        )
        /
        LAG(revenue) OVER(ORDER BY sales_month)
        * 100,
    2) AS growth_percentage
FROM monthly_sales;

-- 5 The top 10 products that generate the most revenues

SELECT products.product_category_name, SUM(payments.payment_value) AS revenue
FROM products
JOIN order_items ON products.product_id = order_items.product_id
JOIN payments ON payments.order_id = order_items.order_id
GROUP BY products.product_category_name
ORDER BY SUM(payments.payment_value) DESC
LIMIT 10;

-- 6 the highest value customers
SELECT
    c.customer_unique_id,
    SUM(p.payment_value) AS total_spending
FROM customer_cleaned c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN payments p
ON o.order_id = p.order_id
GROUP BY c.customer_unique_id
ORDER BY total_spending DESC
LIMIT 3;

-- 7 caculating the number of orders per customer
SELECT
    c.customer_unique_id,
    COUNT(DISTINCT o.order_id) AS number_of_orders
FROM customer_cleaned c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_unique_id
ORDER BY number_of_orders DESC;

-- 8 where the customers are located
SELECT DISTINCT geolocation_city AS City, geolocation_state AS state
FROM location_cleaned;

-- 9 how customers pay
SELECT payment_type, COUNT(payment_type) AS Number_Of_Orders FROM payments
GROUP BY payment_type;

-- 10 the products that sold the most
SELECT 
products.product_category_name AS Product_Category, SUM(payments.payment_value) AS Payment
FROM products
JOIN order_items ON order_items.product_id = products.product_id
JOIN payments ON payments.order_id = order_items.order_id
GROUP BY Product_Category
ORDER BY Payment DESC;

-- 11 Which products generate high revenue but low sales volume?
WITH product_performance AS
(
    SELECT
        oi.product_id,
        p.product_category_name,
        COUNT(*) AS sales_volume,
        ROUND(SUM(oi.price),2) AS total_revenue,
        ROUND(AVG(oi.price),2) AS average_price
    FROM order_items oi
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY
        oi.product_id,
        p.product_category_name
)

SELECT *
FROM product_performance
ORDER BY total_revenue DESC;

-- 12 Which sellers perform best
SELECT
    s.seller_id,
    ROUND(SUM(oi.price),2) AS total_revenue,
    COUNT(DISTINCT oi.order_id) AS total_orders,
    ROUND(AVG(r.review_score),2) AS average_rating
FROM sellers s
JOIN order_items oi
    ON s.seller_id = oi.seller_id
JOIN orders o
    ON oi.order_id = o.order_id
LEFT JOIN reviews r
    ON o.order_id = r.order_id
GROUP BY s.seller_id
ORDER BY total_revenue DESC;